### ISSUE TITLE
Merchant never uses dispute status

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/zkchannels-spec#98]
If the merchant detects cheating by the customer during unilateral close, they should set a channel status of `Dispute` when they call the `MerchDispute` entrypoint.

**Comment by marsella** [comment]
That makes sense to me. The implementation currently
- checks for the revocation secret. If it exists,
- set status to `Dispute`
- post `merchDispute` entrypoint
- once confirmed, set status to `Closed`
